#!/usr/bin/env sh

## Description: Installs Drupal CMS and prepares it for local development. This is only meant for contributing changes to Drupal CMS; it is not for setting up a project built with Drupal CMS.
## Usage: drupal-install
## Example: "ddev drupal-install"

# Install Drupal CMS.
composer drupal:install

# If we don't have `sendmail`, use the test mail collector.
which sendmail || drush config:set --yes system.mail interface.default test_mail_collector

# Additional tweaks for development, if we're not running in CI.
if [ -z "$CI" ]; then
  composer require --dev drupal/default_content:^2@alpha
  drush install --yes default_content
  drush user:password editor editor
  drush user:unblock editor
  drush config:set --yes system.logging error_level verbose
fi
