#!/usr/bin/env sh

## Description: Installs Drupal CMS and prepares it for local development. This is only meant for contributing changes to Drupal CMS; it is not for setting up a project built with Drupal CMS.
## Usage: drupal-install
## Example: "ddev drupal-install"

composer install
drush site:install --yes --account-pass admin
drush config:set --yes system.logging error_level verbose
drush install --yes default_content
drush user:password editor editor
drush user:unblock editor
