#!/usr/bin/env sh

## Description: Runs Drupal CMS's automated test suite.
## Usage: run-tests
## Example: "ddev run-tests"

# Disable deprecation notices because they can cause PHPUnit to exit with a non-zero
# status, and there's often nothing we can do about them.
export SYMFONY_DEPRECATIONS_HELPER=disabled

# Set up the environment variables needed for isolated PHPUnit tests.
export SIMPLETEST_BASE_URL=$DDEV_PRIMARY_URL

# Run the test suite.
cd $DDEV_DOCROOT && phpunit --testdox --configuration core recipes
